return {
    settings = {
        gopls = {
            gofumpt = true,
            codelenses = {
                gc_details = false,
                generate = true,
                regenerate_cgo = true,
                run_govulncheck = true,
                test = true,
                tidy = true,
                upgrade_dependency = true,
                vendor = true,
            },
            hints = {
                assignVariableTypes = true,
                compositeLiteralFields = true,
                compositeLiteralTypes = true,
                constantValues = true,
                functionTypeParameters = true,
                parameterNames = true,
                rangeVariableTypes = true,
            },
            analyses = {
                S1002 = true,
                S1011 = true,
                S1016 = true,
                S1021 = true,
                S1025 = true,
                SA1000 = true,
                SA1002 = true,
                SA1014 = true,
                SA1020 = true,
                SA1029 = true,
                SA1032 = true,
                SA2002 = true,
                SA4005 = true,
                SA4006 = true,
                SA4008 = true,
                SA4010 = true,
                SA4023 = true,
                SA4031 = true,
                SA5000 = true,
                SA5007 = true,
                SA6000 = true,
                SA6001 = true,
                SA9001 = true,
                SA9005 = true,
                ST1005 = true,
                ST1000 = false,
                slicesdelete = true,
            },
            usePlaceholders = false,
            completeUnimported = true,
            staticcheck = true,
            directoryFilters = { "-.git", "-.vscode", "-.idea", "-.vscode-test", "-node_modules" },
            semanticTokens = true,
        },
    },
}
